_BASE_: "./Base_hsil_norm_baseline.yaml"

OUTPUT_DIR: '/data/lxc/output/Cervix_Detection-master/faster_r50_c4/hsil_norm_baseline/acid_steps153_lr0.002'

DATASETS:
  CERVIX_DATA_TYPE: 'acid'

SOLVER:
  STEPS: (15000, 30000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.002
