_BASE_: "../Base_cervix_faster_rcnn_c4.yaml"

DATASETS:
  CERVIX_SPLIT_PATH_TRAIN: '/data/ctt/data/CervixData/paper_data/hsil_norm/train.txt'
  CERVIX_SPLIT_PATH_VALID: '/data/lxc/Cervix/paper_data/data_split/det/hsil/valid.txt'
  CERVIX_SPLIT_PATH_TEST: '/data/lxc/Cervix/paper_data/data_split/det/hsil/test.txt'
  CERVIX_LABEL_TYPE: 'hsil'

MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
