_BASE_: "./Base_hsil.yaml"

OUTPUT_DIR: '/data/ctt/output/Cervix_Detection-master/retinanet_r50_fpn/hsil/acid_steps153_lr0.002'

DATASETS:
  CERVIX_DATA_TYPE: 'acid'

SOLVER:
  STEPS: (15000, 30000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.002

TEST:
  EVAL_PERIOD: 1000