_BASE_: "../Base_cervix_retinanet_r50_fpn.yaml"

DATASETS:
  CERVIX_SPLIT_PATH_TRAIN: '/data/lxc/Cervix/paper_data/data_split/det/hsil/train.txt'
  CERVIX_SPLIT_PATH_VALID: '/data/lxc/Cervix/paper_data/data_split/det/hsil/valid.txt'
  CERVIX_SPLIT_PATH_TEST: '/data/lxc/Cervix/paper_data/data_split/det/hsil/test.txt'
  CERVIX_LABEL_TYPE: 'hsil'

MODEL:
  RETINANET:
    NUM_CLASSES: 1
