_BASE_: "./Base_hsil.yaml"

OUTPUT_DIR: '/data/ctt/output/Cervix_Detection-master/retinanet_r50_fpn/hsil/iodine_steps051_lr0.005'

DATASETS:
  CERVIX_DATA_TYPE: 'iodine'

SOLVER:
  STEPS: (5000, 10000)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.005

TEST:
  EVAL_PERIOD: 1000