_BASE_: "./Base_hsil_norm.yaml"

OUTPUT_DIR: '/data/ctt/output/Cervix_Detection-master/retinanet_r50_fpn/hsil_norm/acid_cam0.2_steps102_lr0.002'

DATASETS:
  CERVIX_DATA_TYPE: 'acid'

MODEL:
  CAM_LOSS_WEIGHT: 0.2

SOLVER:
  STEPS: (10000, 20000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.002

TEST:
  EVAL_PERIOD: 1000