_BASE_: "./Base_hsil_norm.yaml"

OUTPUT_DIR: '/data/ctt/output/Cervix_Detection-master/retinanet_r50_fpn/hsil_norm/acid_cam0.3_steps153_lr0.002'

DATASETS:
  CERVIX_DATA_TYPE: 'acid'

MODEL:
  CAM_LOSS_WEIGHT: 0.3

SOLVER:
  STEPS: (15000, 30000)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.002

TEST:
  EVAL_PERIOD: 1000