_BASE_: "./Base_hsil_norm.yaml"

OUTPUT_DIR: '/data/ctt/output/Cervix_Detection-master/retinanet_r50_fpn/hsil_norm/acid_cam0.2_steps153_lr0.0005'

DATASETS:
  CERVIX_DATA_TYPE: 'acid'

MODEL:
  CAM_LOSS_WEIGHT: 0.2

SOLVER:
  STEPS: (15000, 30000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.0005

TEST:
  EVAL_PERIOD: 1000