_BASE_: "./Base_hsil_norm_baseline.yaml"

OUTPUT_DIR: '/data/lxc/output/Cervix_Detection-master/retinanet_r50_fpn/hsil_norm_baseline/acid_debug'

DATASETS:
  CERVIX_DATA_TYPE: 'acid'
  TEST: ("cervix_valid", "cervix_test")
  EVAL: ("cervix_valid",)

SOLVER:
  VIS_PERIOD: 30

TEST:
  EVAL_PERIOD: 60